---
- hosts: all
  gather_facts: false
  
  tasks:
  - name: Get IP for VM
    delegate_to: localhost
    vsphere_guest:
        vmware_guest_facts: true
        vcenter_hostname: "192.168.200.161"
        username: "a-dhr"
        password: "Garfield11"
        guest: "{{ inventory_hostname }}"
    register: newvm

  - name: Wait for 60 sec for VM Tools to start    
    pause: seconds=60
    when: newvm.ansible_facts.hw_eth0.ipaddresses[0] is undefined
    
    
  - name: debug facts
    debug: msg="vmguest facts are {{ newvm.ansible_facts.hw_name }}"
    tags: vmfacts