---
    - name: Configure hostname
      hostname: name={{ inventory_hostname }}
    - name: upgrade all packages
      yum: name=* state=latest 
    - name: Install Nano
      yum: name=nano state=present
    - name: Install libselinux-python
      yum: name=libselinux-python state=present    
    - name: Build hosts file
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_default_ipv4.address is defined
      with_items: groups['all']