---
    - name: Configure hostname
      hostname: name={{ inventory_hostname }}
    - name: upgrade all packages
      yum: name=* state=latest 
    - name: Install Nano
      yum: name=nano state=present
    - name: Install libselinux-python
      yum: name=libselinux-python state=present    
