---
    - name: Configure hostname
      hostname: name={{ inventory_hostname }}
    - name: upgrade all packages
      yum: name=* state=latest 
    - name: Install Nano
      yum: name=nano state=present
    - name: Install libselinux-python
      yum: name=libselinux-python state=present 

    - name: Install firewalld
      yum: name=firewalld state=present 
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"            
      
    - name: Start and enable firewalld
      action: service name=firewalld enabled=yes state=restarted  
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"   
            
    - name: Build hosts file
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_default_ipv4.address is defined
      with_items: groups['all']